import Hellinger.ProductState
import Hellinger.ProductStateProperties
import Hellinger.PosteriorState
import Hellinger.ParityBlocks
import Hellinger.ChannelSections
import Hellinger.F2Model
import Hellinger.ColumnSelection
import Hellinger.PivotCoordinates
import Hellinger.ShearNoise
import Hellinger.LinearQuotient
import Hellinger.F2Fourier
import Hellinger.SpinState
import Hellinger.ReflectionCounterexample
import Hellinger.CutNorm
import Hellinger.ProductStateSemantics
import Hellinger.QuotientInformation
import Hellinger.Fourier
import Hellinger.FourierCounting
import Hellinger.FourierProducts
import Hellinger.FourierRigidity
import Hellinger.FlatnessConsequences
import Hellinger.AntipodalEquality
import Hellinger.StrictJensen
import Hellinger.PosteriorGram
import Hellinger.TranslationEquality
import Hellinger.TranslationInformation

#print axioms Hellinger.ProductState.state_diagonalization
#print axioms Hellinger.ProductStateProperties.state_posSemidef
#print axioms Hellinger.PosteriorState.bsc_lifting
#print axioms Hellinger.ParityBlocks.antipodal_hellinger
#print axioms Hellinger.ChannelSections.translation_hellinger
#print axioms Hellinger.F2Model.noise_apply_bits
#print axioms Hellinger.ColumnSelection.exists_column_basis
#print axioms Hellinger.PivotCoordinates.quotient_coordinate_formula
#print axioms Hellinger.ShearNoise.shear_convex_comparison
#print axioms Hellinger.LinearQuotient.linear_quotient_comparison
#print axioms Hellinger.F2Model.bent_linearEquiv
#print axioms Hellinger.SpinState.state_gibbs
#print axioms Hellinger.ReflectionCounterexample.reflection_counterexample
#print axioms Hellinger.CutNorm.product_state_cut_identity
#print axioms Hellinger.ProductStateSemantics.antipodal_iff_anticommutes
#print axioms Hellinger.QuotientInformation.linear_quotient_information
#print axioms Hellinger.Fourier.inversion
#print axioms Hellinger.Fourier.parseval
#print axioms Hellinger.Fourier.walsh_noise
#print axioms Hellinger.Fourier.card_degree
#print axioms Hellinger.Fourier.card_even_degree
#print axioms Hellinger.FourierProducts.noise_fourth_moment
#print axioms Hellinger.Fourier.signed_dictator_of_noise_equality
#print axioms Hellinger.Flatness.dimension_even
#print axioms Hellinger.Flatness.no_sign_reversing_translation
#print axioms Hellinger.AntipodalEquality.objective_equality_iff_signed_dictator
#print axioms Hellinger.root_strictConcave
#print axioms Hellinger.UniformChannel.root_mean_equality_iff
#print axioms Hellinger.PosteriorGram.signed_dictator_of_lifting_and_objective_equality
#print axioms Hellinger.TranslationEquality.translation_equality
#print axioms Hellinger.TranslationInformation.translation_information
